<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Module" data-toc-modified-id="Module-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Module</a></span></li><li><span><a href="#S&amp;P500-rate-of-return-by-Sector" data-toc-modified-id="S&amp;P500-rate-of-return-by-Sector-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>S&amp;P500 rate of return by Sector</a></span></li></ul></div>

## Module

In [2]:
import yfinance as yf
import pandas as pd
import numpy as np

## S&P500 rate of return by Sector

In [16]:
# Communication Services XLC : 통신 - 통신, 방송, 엔터
# Consumer Discretionary XLY : 임의소비재 - 자동차, 내구제, 서비스, 유통
# Consumer Staples XLP : 필수소비재 - 식료품 소매, 식음료, 개인용품
# Energy XLE : 에너지 - 에너지 장비 및 서비스, 오일, 가스
# Financials XLF : 금융 - 은행, 금융기관, 보험
# Heath Care XLV : 의료 - 의료장비 및 서비스, 의약 및 생명과학
# Industrials XLI : 산업 - 자본재, 상업서비스, 운송
# Materials XLB : 재료 - 화학, 건자재, 포장용기, 금속, 광물, 목재
# Real Estate XLRE : 부동산 - 리츠, 부동산 개발 및 관리
# Technology XLK : 정보기술- 반도체, 소프트웨어, 기술장비
# Utilities XLU : 유틸리트 - 전기, 가스, 수도

In [38]:
ticker_usd = ['^GSPC', 'XLC', 'XLY', 'XLP', 'XLE', 'XLF', 'XLV', 'XLI', 'XLB', 'XLRE', 'XLRE', 'XLK', 'XLU']
result=yf.download(ticker_usd,start = '2024-01-01')
result.columns = ['_'.join(c) for c in result.columns]
result = result.reset_index()
result['Date'] = result['Date'].dt.strftime('%Y-%m-%d')
result['Date'] = pd.to_datetime(result['Date'])

remain_cols = []
for t in ticker_usd:
    remain_cols.append(f"Close_{t}")

result = result[['Date']+remain_cols]
df = result.dropna()

[*********************100%***********************]  12 of 12 completed

In [62]:
# ISO Calendar를 사용해 'Year'와 'Week'를 추가
df['Year'], df['Week'], _ = zip(*df['Date'].map(lambda x: x.isocalendar()))

# 각 'Year'와 'Week'별로 마지막 Price 선택
df.groupby(['Year', 'Week']).last().reset_index()

,Year,Week,Date,Close_^GSPC,Close_XLC,Close_XLY,Close_XLP,Close_XLE,Close_XLF,Close_XLV,Close_XLI,Close_XLB,Close_XLRE,Close_XLRE,Close_XLK,Close_XLU
0,2024,1,2024-01-05,4697.240234,72.040001,172.619995,72.010002,84.680000,37.750000,139.119995,111.430000,84.339996,39.290001,39.290001,184.119995,64.529999
1,2024,2,2024-01-12,4783.830078,73.809998,173.960007,72.800003,82.680000,37.599998,140.520004,112.110001,83.449997,39.540001,39.540001,192.240005,63.320000
2,2024,3,2024-01-19,4839.810059,74.830002,174.889999,72.050003,80.169998,37.930000,139.460007,112.449997,82.230003,38.700001,38.700001,200.169998,60.980000
3,2024,4,2024-01-26,4890.970215,77.680000,171.679993,72.629997,84.250000,38.650002,139.270004,113.430000,82.510002,38.490002,38.490002,201.750000,61.209999
4,2024,5,2024-02-02,4958.609863,79.739998,177.320007,74.169998,83.519997,38.980000,141.990005,115.580002,83.089996,38.310001,38.310001,202.240005,61.490002
5,2024,6,2024-02-09,5026.609863,79.169998,179.899994,73.110001,83.309998,39.080002,144.009995,116.949997,83.139999,38.410000,38.410000,207.839996,60.270000
6,2024,7,2024-02-16,5005.569824,78.949997,179.020004,73.279999,85.570000,39.630001,145.619995,118.029999,85.169998,38.349998,38.349998,202.570007,61.230000
7,2024,8,2024-02-23,5088.799805,79.720001,181.289993,74.779999,85.959999,40.299999,147.860001,120.220001,86.830002,38.720001,38.720001,205.289993,61.959999
8,2024,9,2024-03-01,5137.080078,80.019997,185.020004,74.459999,87.139999,40.290001,146.339996,121.519997,87.959999,39.540001,39.540001,210.759995,61.720001
9,2024,10,2024-03-08,5123.689941,79.589996,180.309998,75.160004,88.169998,40.619999,146.429993,122.300003,89.349998,40.169998,40.169998,207.350006,63.750000
10,2024,11,2024-03-15,5117.089844,79.290001,178.050003,75.529999,91.559998,40.790001,145.360001,122.040001,90.800003,39.040001,39.040001,205.630005,63.459999
11,2024,12,2024-03-22,5234.180176,81.820000,182.720001,75.639999,92.400002,41.419998,145.440002,125.209999,91.370003,38.619999,38.619999,209.910004,63.860001
12,2024,13,2024-03-28,5254.350098,81.660004,183.889999,76.360001,94.410004,42.119999,147.729996,125.959999,92.889999,39.529999,39.529999,208.270004,65.650002
13,2024,14,2024-04-05,5204.339844,82.519997,178.839996,74.330002,98.080002,41.570000,143.220001,125.669998,92.769997,38.380001,38.380001,206.449997,65.160004
14,2024,15,2024-04-12,5123.410156,81.330002,177.110001,73.379997,96.129997,40.060001,138.910004,122.900002,89.919998,37.240002,37.240002,205.419998,64.199997
15,2024,16,2024-04-19,4967.229980,79.470001,169.759995,74.440002,94.970001,40.380001,138.949997,120.470001,88.959999,35.880001,35.880001,192.529999,65.430000
16,2024,17,2024-04-26,5099.959961,80.110001,175.910004,75.589996,95.739998,40.820000,139.960007,122.660004,89.519997,36.459999,36.459999,199.830002,66.190002
17,2024,18,2024-05-03,5127.790039,80.209999,177.910004,75.879997,92.570000,40.549999,140.830002,122.769997,89.529999,37.020000,37.020000,202.550003,68.410004
18,2024,19,2024-05-10,5222.680176,81.790001,178.100006,77.620003,93.830002,41.830002,143.589996,125.680000,91.839996,37.810001,37.810001,205.539993,71.269997
19,2024,20,2024-05-17,5303.270020,82.610001,178.699997,78.209999,94.959999,42.490002,146.309998,125.330002,92.150002,38.759998,38.759998,211.820007,72.339996
20,2024,21,2024-05-24,5304.720215,82.949997,175.539993,77.099998,91.370003,41.610001,144.419998,124.459999,91.360001,37.349998,37.349998,215.190002,71.500000
21,2024,22,2024-05-31,5277.509766,83.260002,175.970001,77.339996,93.199997,41.639999,143.699997,123.510002,91.529999,38.049999,38.049999,210.160004,72.720001
22,2024,23,2024-06-07,5346.990234,84.400002,177.660004,77.660004,89.989998,41.480000,146.429993,122.330002,89.790001,37.970001,37.970001,215.600006,69.940002
23,2024,24,2024-06-14,5431.600098,84.129997,178.330002,76.949997,88.040001,40.650002,145.880005,121.150002,88.980003,38.529999,38.529999,227.669998,69.940002
24,2024,25,2024-06-21,5464.620117,84.940002,182.610001,77.669998,89.750000,41.330002,146.809998,122.970001,89.639999,38.480000,38.480000,228.410004,69.389999
25,2024,26,2024-06-28,5460.479980,85.660004,182.399994,76.580002,91.150002,41.110001,145.750000,121.870003,88.309998,38.410000,38.410000,226.229996,68.139999
26,2024,27,2024-07-05,5567.189941,87.760002,189.300003,77.379997,90.099998,41.540001,144.410004,121.220001,87.900002,38.299999,38.299999,232.880005,68.550003
27,2024,28,2024-07-12,5615.350098,86.309998,191.490005,77.449997,90.519997,42.380001,148.270004,124.180000,90.500000,39.990002,39.990002,233.800003,71.260002
28,2024,29,2024-07-19,5505.000000,85.110001,187.809998,78.089996,92.370003,42.849998,147.869995,124.870003,90.110001,40.509998,40.509998,220.869995,70.129997
29,2024,30,2024-07-26,5459.100098,83.699997,182.610001,78.489998,92.190002,43.410000,149.960007,126.300003,91.330002,40.730000,40.730000,216.279999,71.169998
30,2024,31,2024-08-02,5346.560059,84.739998,176.160004,79.260002,88.400002,42.060001,150.860001,122.730003,90.040001,41.860001,41.860001,204.720001,74.220001
31,2024,32,2024-08-09,5344.160156,85.209999,174.339996,79.150002,89.410004,42.400002,149.979996,124.279999,88.559998,41.810001,41.810001,205.630005,73.610001
32,2024,33,2024-08-16,5554.250000,86.260002,183.130005,80.510002,90.470001,43.770000,152.869995,126.970001,90.570000,41.860001,41.860001,221.399994,74.440002
33,2024,34,2024-08-23,5634.609863,87.500000,187.869995,81.839996,90.389999,44.430000,155.449997,129.279999,92.730003,43.369999,43.369999,223.960007,75.419998
34,2024,35,2024-08-30,5648.399902,87.320000,187.119995,82.510002,91.279999,45.740002,157.199997,131.460007,94.279999,43.549999,43.549999,220.330002,76.290001
35,2024,36,2024-09-06,5408.419922,83.769997,182.399994,82.989998,86.010002,44.290001,153.949997,125.889999,89.889999,43.630001,43.630001,203.919998,75.910004
36,2024,37,2024-09-13,5626.020020,86.870003,192.479996,83.930000,85.589996,44.509998,156.160004,130.570007,92.690002,45.209999,45.209999,220.440002,78.540001
37,2024,38,2024-09-20,5702.549805,88.900002,196.690002,83.050003,88.760002,45.660000,155.279999,133.179993,94.070000,44.680000,44.680000,222.529999,80.080002
38,2024,39,2024-09-27,5738.169922,90.010002,200.839996,83.019997,87.190002,45.150002,153.020004,134.830002,96.919998,44.290001,44.290001,225.100006,80.419998
39,2024,40,2024-10-04,5751.069824,90.879997,198.169998,81.470001,93.180000,45.650002,151.639999,135.509995,95.169998,43.520000,43.520000,225.289993,81.309998
40,2024,41,2024-10-11,5815.029785,90.430000,196.580002,81.639999,92.809998,46.509998,153.889999,138.419998,95.889999,43.430000,43.430000,230.809998,79.250000
41,2024,42,2024-10-18,5864.669922,91.230003,199.509995,82.239998,90.339996,47.619999,153.130005,139.270004,97.629997,44.740002,44.740002,230.910004,81.949997
42,2024,43,2024-10-25,5808.120117,90.849998,200.809998,81.059998,89.769997,46.630001,148.589996,135.399994,93.959999,44.070000,44.070000,230.289993,80.379997
43,2024,44,2024-11-01,5728.799805,92.400002,200.089996,80.150002,88.029999,46.639999,147.740005,134.009995,93.129997,42.740002,42.740002,223.910004,78.129997
44,2024,45,2024-11-08,5995.540039,96.180000,215.119995,80.820000,93.750000,49.189999,150.179993,142.089996,94.470001,43.910000,43.910000,237.160004,79.180000
45,2024,46,2024-11-15,5870.620117,95.150002,213.440002,79.959999,94.730003,49.869999,141.839996,139.110001,91.279999,42.980000,42.980000,228.710007,79.250000
46,2024,47,2024-11-21,5948.709961,97.089996,215.000000,81.089996,97.120003,50.169998,144.029999,140.690002,93.570000,43.759998,43.759998,233.479996,81.889999

In [77]:
pd.concat(df[['Year', 'Week']], np.round(df[cols['ticker']].pct_change()*100, 2))

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

In [82]:
df_sector = pd.concat([df[['Year', 'Week']], np.round(df[cols['ticker']].pct_change()*100, 2)], axis=1)

In [88]:
df_sector = df_sector.groupby(['Year', 'Week']).last().reset_index()

In [103]:
df_sector_maxWeek = df_sector[
    (df_sector['Year'] == df_sector['Year'].max())
    & (df_sector['Week'] == df_sector['Week'].max())
]

In [104]:
df_sector_maxWeek

,Year,Week,Close_^GSPC,Close_XLC,Close_XLY,Close_XLP,Close_XLE,Close_XLF,Close_XLV,Close_XLI,Close_XLB,Close_XLRE,Close_XLRE,Close_XLRE,Close_XLRE,Close_XLK,Close_XLU
46,2024,47,0.53,-0.26,0.18,1.08,0.81,1.27,0.8,1.25,1.22,0.67,0.67,0.67,0.67,1.02,1.74

In [ ]:
import seaborn as sns

In [ ]:
impor

In [100]:
df_sector['Year'].max()

2024

In [73]:
np.round(df[cols['ticker']].pct_change()*100, 2)

,Close_^GSPC,Close_XLC,Close_XLY,Close_XLP,Close_XLE,Close_XLF,Close_XLV,Close_XLI,Close_XLB,Close_XLRE,Close_XLRE,Close_XLRE,Close_XLRE,Close_XLK,Close_XLU
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.80,-0.37,-2.02,-0.78,1.63,-0.85,-0.17,-1.49,-1.08,-2.37,-2.37,-2.37,-2.37,-1.02,0.37
2,-0.34,-0.33,-0.70,-0.14,-1.75,0.40,0.50,0.13,-0.32,-0.25,-0.25,-0.25,-0.25,-0.73,-0.31
3,0.18,0.42,0.16,-0.22,0.08,0.43,-0.09,0.12,0.17,-0.20,-0.20,-0.20,-0.20,-0.03,0.37
4,1.41,1.55,1.70,0.74,-1.16,0.64,0.88,0.66,0.43,1.37,1.37,1.37,1.37,2.51,0.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,-1.32,-2.00,-0.85,-0.88,-0.15,0.46,-1.85,-0.54,-0.70,0.12,0.12,0.12,0.12,-2.48,1.50
222,0.39,0.99,0.92,0.70,1.33,0.30,0.07,-0.14,0.78,0.88,0.88,0.88,0.88,0.32,0.87
223,0.40,0.66,0.07,0.14,-0.64,-0.66,-0.51,-0.09,-0.33,0.42,0.42,0.42,0.42,0.82,0.64
224,0.00,0.64,-0.44,-0.51,1.01,-0.30,1.18,0.11,0.82,-0.16,-0.16,-0.16,-0.16,-0.09,0.05
225,0.53,-0.26,0.18,1.08,0.81,1.27,0.80,1.25,1.22,0.67,0.67,0.67,0.67,1.02,1.74

In [65]:
df['Close_XLY'].pct_change()*100

0           NaN
1     -2.020879
2     -0.702887
3      0.156652
4      1.703164
         ...
221   -0.854699
222    0.922977
223    0.074279
224   -0.440698
225    0.177059
Name: Close_XLY, Length: 226, dtype: float64

In [66]:
cols = {}
cols['ticker'] = [c for c in df.columns if 'Close' in c]

In [67]:
cols['ticker']

['Close_^GSPC',
 'Close_XLC',
 'Close_XLY',
 'Close_XLP',
 'Close_XLE',
 'Close_XLF',
 'Close_XLV',
 'Close_XLI',
 'Close_XLB',
 'Close_XLRE',
 'Close_XLRE',
 'Close_XLK',
 'Close_XLU']